### ISSUE TITLE
whyd u delete ur virus repo

### ISSUE THREAD

**Issue by ffluxxus** [MiningTcup/YouClient#1]
grrrrr

**Comment by ffluxxus** [comment]
oh and btw ur code i suspicious. direct api key exposure, cross site scripting and no security headers.

**Comment by MiningTcup** [comment]
Because you kept claiming it was a virus when it wasn't. I no longer support it and can't deal with whining 8-year-olds playing Roblox. I don't even use Windows any mroe.

**Comment by MiningTcup** [comment]
I will report you if you keep harassing me, I'm not joking, it wasn't a virus.

**Comment by MiningTcup** [comment]
Also, about the direct key exposure, it's completely client-side, what am I supposed to do, if you're so smart?
